In [23]:
import numpy as np

# 0차원
- numpy array는 1 또는 5,10 같이 숫자 데이터를 array화 해줄 수 있음

In [24]:
arr = np.array(6)

### Scalar로 들어갔을 때는 shape가 아무것도 없는 것으로 나옴

In [25]:
arr.ndim

0

In [26]:
arr.shape

()

# 1차원
- 숫자가 10과 같이 하나만 들어간다 해도 리스트를 한번 씌우게 되면 차원이 생김
- 1차원에 3개의 값이 들어갔다는 의미
- 해석하자면 1차원에 3개의 값이 들어감

In [27]:
arr = np.array([10])
arr

array([10])

In [28]:
arr.shape

(1,)

In [29]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [30]:
arr.shape

(3,)

# 2차원
- 대괄호를 추가적으로 씌우면 차원이 추가적으로 하나 생김
- 차원이 2개가 있고, 각 차원 마다 각각 3개의 값이 들어있다고 생각하면 됨

In [33]:
arr = np.array([[1,2,3]])
arr

array([[1, 2, 3]])

In [34]:
arr.shape

(1, 3)

In [36]:
arr = np.array([[1,2,3],[1,2,3],[1,2,3]])
arr.shape

(3, 3)

- 참고로 0차원 숫자에 대괄호를 2번 씌우면 두개의 차원이 됨

In [41]:
arr = np.array([[10]])
arr.shape

(1, 1)

# 다 차원

In [45]:
arr = np.array([[[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]],[[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]]])
arr.shape

(2, 2, 3, 3)

In [46]:
arr

array([[[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]],


       [[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]]])

In [47]:
arr = np.array([[[1],[2],[3]],[[1],[2],[3]],[[1],[2],[3]]])

In [48]:
arr.shape

(3, 3, 1)